### ISSUE TITLE
ddev-redis-commander needs a knowledgable maintainer

### ISSUE THREAD

**Issue by rfay** [ddev/ddev-redis-commander#1]
Hi @graloth - would you be willing to lead the maintenance of this project? It just means subscribing to all activity and helping people out when things need to be improved in issues or PRs. I'll also help maintain.

It's best for the lead maintainer to be a regular user of the project of course.

**Comment by rfay** [comment]
@julienloizelet would you be willing to be the lead maintainer of this add-on? Seems you use it!

**Comment by julienloizelet** [comment]
> @julienloizelet would you be willing to be the lead maintainer of this add-on? Seems you use it!

It would be a pleasure. Thanks.

**Comment by rfay** [comment]
I'm thrilled! You have the privileges. When ready, do a release; and of course update the README to put your name at the bottom :)

**Comment by tyler36** [comment]
Yay!
