### ISSUE TITLE
[BUG] The service is set to restart "always" 

### ISSUE THREAD

**Issue by dkd-kaehm** [ddev/ddev-redis-commander#14]
The service MUST NOT always restart.

**Comment by tyler36** [comment]
@dkd-kaehm 
What kind of problem do you encounter if the service is set to always restart?

**Comment by rfay** [comment]
I do see that it has this: https://github.com/ddev/ddev-redis-commander/blob/d649ea68144710842c908e29d793f58e208fe348/docker-compose.redis-commander.yaml#L9

My general strategy has been to not auto-restart with containers, just because when they fail there's almost always a reason.

**Comment by dkd-kaehm** [comment]
> @dkd-kaehm What kind of problem do you encounter if the service is set to always restart?

If project is stopped this service bobbing around without needs and any purpose.

**Comment by rfay** [comment]
I wouldn't think that would happen when the project is stopped explicitly. Can you verify that that is what happened? It shouldn't be auto-restarting when project is stopped. I'll bet what's happening to you is you're stopping and restarting Docker and seeing this. A very good reason to use the default behavior.

**Comment by dkd-kaehm** [comment]
> I wouldn't think that would happen when the project is stopped explicitly. Can you verify that that is what happened? It shouldn't be auto-restarting when project is stopped. I'll bet what's happening to you is you're stopping and restarting Docker and seeing this. A very good reason to use the default behavior.

Yes you are rigth, it happens after reboot of system or docker restart.
But anyway all standard services and almost all used by me ddev plugins do not behave like this.
