### ISSUE TITLE
Listen port describe in README is not the same for HTTP

### ISSUE THREAD

**Issue by sbrindle** [ddev/ddev-redis-commander#17]
Hello,

In the README, you ask to launch Redis Commander in the browser on port 1359. Otherwise, the Redis Command service listens on port 1358 (for HTTP request).
![Image](https://github.com/user-attachments/assets/59a0f1ed-10ef-4c0d-9a8d-1677b6590900)

Sincerely,

**Comment by rfay** [comment]
Hi @sbrindle - It's not clear to me exactly what you're saying or what you're showing in your screenshot. If you can give more detail, we'll be happy to discuss.

**Comment by sbrindle** [comment]
Hello,
My screenshot is the result of a « docker ps » command.
The redis commander service of my DDev stack expose the port 1358 and not 1359. 

That’s why in my browser I need to use the port 1358 with my project url.

**Comment by julienloizelet** [comment]
Hi @sbrindle ,

Thanks for your message.

if you run `ddev describe`, do you see `https://<project>.ddev.site:1359` or   `https://<project>.ddev.site:1358` for the redis-commander service ?

In my test, I see  `https://<project>.ddev.site:1359`  (as mentioned in the README), and I can access the Redis commander UI with this url: 

![Image](https://github.com/user-attachments/assets/612a6291-cfc4-425b-9359-ef9b7100b547)


Thanks

**Comment by sbrindle** [comment]
I see 1358 port but with http (not https).

**Comment by julienloizelet** [comment]
> I see 1358 port but with http (not https).

Well, I don't know why you don't have https available (perhaps @rfay can tell us more about it), 

but at least, the `ddev describe` command is showing you the correct url. 

Thanks

**Comment by stasadev** [comment]
@sbrindle, did you run `mkcert -install` ?

This is a part of [DDEV Installation](https://ddev.readthedocs.io/en/stable/users/install/ddev-installation/).

Without mkcert, DDEV can only work with HTTP, not HTTPS.

**Comment by sbrindle** [comment]
The usage of DDEV in HTTPS is not mandatory even if DDEV actually offers to use it in HTTPS.

As mentioned in the ticket creation, I access my DDEV environment using HTTP (and not HTTPS). :)

If you consider that my ticket is a false anomaly, no problem closing it. I would just have liked a mention in the case of use in HTTP where port 1358 must be used.

Regards

**Comment by stasadev** [comment]
As @julienloizelet said earlier, all ports are in `ddev describe`, so this issue is only about not saying about the port for HTTP in `README.md`.

> I would just have liked a mention in the case of use in HTTP where port 1358 must be used.

I think adding a `ddev redis-commander` command (similar to [this](https://github.com/ddev/ddev-xhgui/blob/main/commands/host/xhgui)), and updating `README.md` would suit your needs. Contributions are welcome!

**Comment by julienloizelet** [comment]
> I think adding a `ddev redis-commander` command (similar to [this](https://github.com/ddev/ddev-xhgui/blob/main/commands/host/xhgui)), and updating `README.md` would suit your needs. 

Excellent idea: this will be a great improvement and people will no longer have to read the result of the `ddev describe` command.

I will work on this and update the README accordingly.

Thanks everyone.
