### ISSUE TITLE
[FEATURE REQUEST] : decrease the health check timeout

### ISSUE THREAD

**Issue by julienloizelet** [ddev/ddev-redis-commander#7]
Hi,

every time I use this add-on, the `ddev start` command takes much longer than usual.

I think the 10 seconds timeout setting for the health check is the main cause, but when I tried to set a lower value (e.g. 5 seconds), it seems that something goes wrong and the `ddev start` command gets stuck.

I am not sure if it is possible to improve this behavior : Any idea how to start working on it?

Thanks

**Comment by rfay** [comment]
It's not hard to decrease the timeout with a `docker-compose.*.yaml`, but this probably means that your redis container is taking forever to become ready. 

If you don't care about ddev saying everything is ready when the redis container is *not* ready, you can remove these lines:

https://github.com/ddev/ddev-redis-commander/blob/19679b4744c75e214f48103c42a534656ce5a185/docker-compose.redis-commander.yaml#L23-L24

**Comment by julienloizelet** [comment]
Well, 
I did some tests and removing the `depends-on` and decreasing the timeout did not change the behavior.

I created a ddev test project with only redis and redis-commander add-on : 

- `ddev restart` took 1m11s with default yaml 

![redis-commander-default](https://user-images.githubusercontent.com/20956510/222331673-32ecc5e6-809f-40b4-a9b3-ff12a2dfa7ee.png)

- `ddev restart` took 1m6s after setting timeout to 2s and removing the `depend-on:redis` part

![redis-commander-timeout-2-and-no-depends-on](https://user-images.githubusercontent.com/20956510/222331821-ae09b9d5-6b7a-49da-814b-9d8f114ebaa3.png)

- `ddev restart` took 14s after removing the redis-commander yaml file

![redis-commander-no-redis-commander](https://user-images.githubusercontent.com/20956510/222331913-154ef7c9-8a4c-42d2-bad5-a0d4012b7993.png)

When it takes more than 1 minute, there is a pause between the `Container ddev-router  Running `step and the `Restarted ddev-redis-commander-test ` step.


I tried `ddev logs -s ddev-router`  (and redis, redis-commander) but I didn't see anything useful to understand this one minute difference.

**Comment by tyler36** [comment]
@julienloizelet 

> I created a ddev test project with only redis and redis-commander add-on :

Can you share the link to the test project? It might help others debug the problem.

**Comment by julienloizelet** [comment]
Hi @tyler36,

I don't have a public repository for that test. I just created it in my local environment with the following commands: 

```
ddev config --project-type=php --project-name=ddev-redis-commander-test
ddev get ddev/ddev-redis
ddev get ddev/ddev-redis-commander
```

Furthermore, I just discovered that the one minute delay I noticed is (probably) just coming from the original Docker file : https://github.com/joeferner/redis-commander/blob/v0.8.1/Dockerfile#L39

But I don't know the best way to improve it.

**Comment by tyler36** [comment]
Confirmed. 

Getting the same issue following the steps above. 

- Only `ddev-redis`, startup is around 20 secs.
- `ddev-redis` & `ddev-redis-commander`, 1min 8-17 secs

Looks like the addon is using this image: https://github.com/joeferner/redis-commander/pkgs/container/redis-commander
Currently the addon is set to use `image: ghcr.io/joeferner/redis-commander:latest` and there looks to be a new release 13 hours ago.

Tried both `ghcr.io/joeferner/redis-commander:0.8.0` and `ghcr.io/joeferner/redis-commander:0.8.1` but still 1+ min startups.

**Comment by rfay** [comment]
Please demonstrate the problem with a trivial project.

It may be that latest redis-commander has its own healthcheck that takes a long time. Please take a look at its repo and see what the healthcheck is; may be worth an issue there...

**Comment by julienloizelet** [comment]
Hi,
Will try to set up a public test project asap.

Should ask too in the redis-commander repo why there is some harcoded `--interval=1m` in the[ Dockerfile](https://github.com/joeferner/redis-commander/blob/v0.8.1/Dockerfile#L39).

Indeed, I tried to play with the `healtcheck` docker-compose option, and it seems that this kind of setting decreases the delay :
```
healthcheck:
  interval: 10s
```
With this, `ddev restart` took less than 20 seconds.

But we probably don't want to test the healthcheck every 10 seconds...

**Comment by rfay** [comment]
It's easy to set up the various healthcheck options to override the Dockerfile default. Just fiddle with the 4 parts of the healthcheck to see what you like and do a PR.

**Comment by julienloizelet** [comment]
Well,
we can indeed easily reduce the health check interval to 10 seconds. 
But that means that the health check will run every 10 seconds instead of every minute, which results in unnecessary resource consumption (maybe not so important ...).

I found other discussions about this docker "issue" ([example](https://github.com/moby/moby/issues/33410)) : the first health check is always run after the "interval" setting; Thus, you have to wait until this "interval" to see your container healthy. And if you set a lower value for the "interval", then the frequency of health check tests will increase.

That's why I am not sure about doing such a PR.

Maybe we could just add some paragraph in the README to say something like : "By default, the redis-commander container will become healthy after 1 minute because the health check is done every minute. If you want to decrease this delay and if you don't mind having a higher health check frequency, you can add the "interval:10s" in the yaml file."

Or even suggest to totally disable the health check with :

```
healthcheck:
    disable:true
```

What do you think ?

**Comment by rfay** [comment]
I think disabling healthcheck on ddev-redis-commander would be fine, and leave the dependency on redis.
